#! /bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5
bspc config active_border_color "#2C363C"
bspc config focused_border_color "#2C363C"
bspc config normal_border_color "#CFC1BA"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# AUTO START
sxhkd &
nitrogen --restore &
picom &
pipewire && pipewire-pulse && wireplumber
setxkbmap -option ctrl:nocaps
xinput set-prop 17 "libinput Accel Profile Enabled" 0, 1, 0
xinput set-prop 17 "libinput Accel Speed" -0.80
/usr/libexec/polkit-gnome-authentication-agent-1 &
